name: RTP
version: 1.0
main: pl.philx.rtp.RTPPlugin
api-version: 1.21
permissions:
  rtp.rtp.use:
    description: Grants access to /rtp command
    default: true
  rtp.rtp.bypasscooldown:
    description: Bypasses the /rtp cooldown
    default: op
  rtp.reload:
    description: Grants access to /reload command
    default: op
  rtp.setrange:
    description: Grants access to /setrange <range> command
    default: op
